name: Build and Test Library

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**', 'Datasync Solution.sln' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**', 'Datasync Solution.sln' ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  DOTNET_CONFIGURATION: 'Release'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup dotnet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore --configuration ${{ env.DOTNET_CONFIGURATION }}

    - name: Build
      run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore

    - name: Run tests
      run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Code coverage summary report
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
